apiVersion: v1
kind: Service
metadata:
  name: master-profile-page-service
spec:
  selector:
    app: master-profile-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30042  # Change to an unused port
  type: NodePort