apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-service-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-deploy-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-deploy-rolebinding
subjects:
- kind: ServiceAccount
  name: jenkins-service-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: jenkins-deploy-role
  apiGroup: rbac.authorization.k8s.io